# Generated by Django 4.0.3 on 2022-04-22 05:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('map', models.URLField(default=None)),
                ('time_to_travel', models.IntegerField(default=None, verbose_name='Travel Duration')),
                ('place_type', models.CharField(choices=[('full day tours', 'Full day tours'), ('day trips', 'Day Trips'), ('private and luxury', 'Private & Luxury')], max_length=200, verbose_name='Place_type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'place',
            },
        ),
    ]
